project:
  type: book
  output-dir: _book

book:
  title: "SWEAT tutorials"
  author: "Emmanuelle Sarrazin"
  date: "2026-10-07"
  chapters:
    - index.qmd
    - docs/trishna_mission.qmd
    - docs/et_models.qmd
    - docs/stic.qmd
    - docs/evaspa.qmd
    - docs/data_preparation.qmd
    - docs/sweat.qmd
    - docs/et_timeseries.qmd
    - docs/references.qmd

format:
  pdf:
    documentclass: scrreprt
    toc: true
