project:
  output-dir: _slides
  render: 
    - docs/

format:
  revealjs:
    theme: dracula
    slide-number: true
    transition: fade         # fade, slide, convex, concave, zoom
    logo: images/trishna_logo.png
    css: css/custom_slide.css
    footer: "SWEAT tutorials"
    template-partials:
      - templates/title-slide.html